;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Data.RotatioDirection",NewTagName="Data.RotationDirection")
+GameplayTagList=(Tag="Data.Capsule.InsertedHole",DevComment="")
+GameplayTagList=(Tag="Data.Capsule.PutOnFloor",DevComment="")
+GameplayTagList=(Tag="Data.Capsule.UpdateCollision",DevComment="")
+GameplayTagList=(Tag="Data.GearPressure",DevComment="")
+GameplayTagList=(Tag="Data.GearPressure.1",DevComment="")
+GameplayTagList=(Tag="Data.GearPressure.2",DevComment="")
+GameplayTagList=(Tag="Data.GearPressure.3",DevComment="")
+GameplayTagList=(Tag="Data.GearPressure.4",DevComment="")
+GameplayTagList=(Tag="Data.GearPressure.5",DevComment="")
+GameplayTagList=(Tag="Data.RotationDirection",DevComment="")
+GameplayTagList=(Tag="Data.RotationDirection.Left",DevComment="")
+GameplayTagList=(Tag="Data.RotationDirection.Right",DevComment="")
+GameplayTagList=(Tag="Dialogues.Glitch.VarA",DevComment="")
+GameplayTagList=(Tag="Dialogues.Mission2.Begin",DevComment="")
+GameplayTagList=(Tag="Dialogues.Mission2.Cantine",DevComment="")
+GameplayTagList=(Tag="Dialogues.Mission2.Pipe",DevComment="")
+GameplayTagList=(Tag="Dialogues.Mission2.TopFreightElevator",DevComment="")
+GameplayTagList=(Tag="Dialogues.Mission2.Valve",DevComment="")
+GameplayTagList=(Tag="Dialogues.Mission2.ValveJump",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.ActivationInput",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.GearAngle",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.GearSpacing",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.LavaDensity",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.1",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.2",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.3",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.4",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.5",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.6",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.7",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.8",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.OilQuantity.9",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.TypeOfGear.A",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.TypeOfGear.B",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.TypeOfGear.C",DevComment="")
+GameplayTagList=(Tag="Game.Board.DevSide.TypeOfGear.D",DevComment="")
+GameplayTagList=(Tag="Game.Board.PlayerSide",DevComment="")
+GameplayTagList=(Tag="Game.Board.PlayerSide.GearPressure",DevComment="")
+GameplayTagList=(Tag="Game.Board.PlayerSide.GearSpacing",DevComment="")
+GameplayTagList=(Tag="Game.Board.PlayerSide.LavaCooling",DevComment="")
+GameplayTagList=(Tag="Game.Board.PlayerSide.LavaDensity",DevComment="")
+GameplayTagList=(Tag="Game.Board.PlayerSide.RotationDirection",DevComment="")
+GameplayTagList=(Tag="Game.Board.PlayerSide.RotationSpeed",DevComment="")
+GameplayTagList=(Tag="Game.Part2.FirstObject",DevComment="")
+GameplayTagList=(Tag="Inputs.Move.Disable",DevComment="")
+GameplayTagList=(Tag="Inputs.Movements.Disable",DevComment="")
+GameplayTagList=(Tag="Players.Dev",DevComment="")
+GameplayTagList=(Tag="Players.Player",DevComment="")
+GameplayTagList=(Tag="Programme.PromptFailed.Classic",DevComment="")
+GameplayTagList=(Tag="Role.Dev",DevComment="Hacker")
+GameplayTagList=(Tag="Role.None",DevComment="No role selected")
+GameplayTagList=(Tag="Role.Player",DevComment="FieldAgent")
+GameplayTagList=(Tag="Trigger.Level2.FirstObject",DevComment="")

